name: Build libspecprober library (Windows - AMD64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Setting up MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: libspecprober compilation
        run: |
          cd interop/libspecprober ; cmake -B build -S . -G "Ninja" -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON ; cmake --build build
      - name: libdxhelper compilation
        run: |
          cd interop/libdxhelper/libdxhelper ; msbuild libdxhelper.sln /p:Configuration=Release /p:Platform=x64
      - name: libspecprober artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "libspecprober library Windows AMD64"
          path: |
            interop/libspecprober/build/specprober.dll
            interop/libdxhelper/libdxhelper/x64/Release/libdxhelper.dll
